version: "3.9"
volumes:
  pgadmin-data:
  pg-data:
services:
  # приложение, которое будет использовать postgres
  app:
    container_name: app
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    # The username under which the app in the container will be started
    user: postgres
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - pg-data:/var/lib/postgresql/data/
      # проброс конфига (можно сделать вместо блока command)
      # - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
       test: ["CMD", "pg_isready", "-U", "${PG_USER}", "-d", "${PG_DB}"]
       interval: 30s
       timeout: 10s
       retries: 5
       start_period: 10s
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.5
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:80